feat(provider): initial release prep
josh-development/utilities pull request #384
Opened 2024-05-13 06:21 UTC by RealShadowNova

Hello team, this PR is crucial as it encompasses the last adjustments we need before the initial release of Josh v2. Everyone assigned, please pull the branch and conduct a thorough review, with special focus on the JoshProvider class functionalities. If you notice anything that could be improved or requires modification, please leave your feedback. It's vital that we resolve all issues with this PR to ensure a smooth launch.

2024-05-13 15:50 UTC, dan-online requested changes

2024-05-13 15:50 UTC, dan-online commented on packages/provider/src/lib/functions/resolveVersion.ts
> + */
```suggestion
 * ```
 */
```

2024-05-15 03:51 UTC, WilsontheWolf requested changes

2024-05-15 03:51 UTC, WilsontheWolf commented on packages/provider/src/lib/types/KeyPath.ts
> + * ```
Are these 2 examples not the same?

2024-07-07 18:48 UTC, merged